version: '3.1'

services:
  tgbot:
    depends_on:
      - tgbot-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://tgbot-db:5432/tgbot-db
    restart: always
  tgbot-db:
    image: postgres
    restart: always
    container_name: tgbot-db
    environment:
      POSTGRES_USER: ${BOT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BOT_DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "tgbot-db"

    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
