version: '3.1'

services:

  tgbot-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "tgbot-db"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  tgbot-db-data:
    name: tgbot-db-data

