spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tgbot-db}
    username: postgres
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cbr:
  api:
    url: http://www.cbr.ru/dailyinfowebserv/dailyinfo.asmx?wsdl

server:
  port: 9090

bot:
  name: TestTelegramBot
  api.key: 5609401876:AAH94ba-xFry3Ipc4HIX4zV4CKKnL6463WM
